// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMusic;

#nullable disable

namespace WebApiMusic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221118210317_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiMusic.Entidades.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Entidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArtistico")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NombreReal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("artista");
                });

            modelBuilder.Entity("WebApiMusic.Entidades.ArtistaDisquera", b =>
                {
                    b.Property<int>("ArtistaId")
                        .HasColumnType("int");

                    b.Property<int>("DisqueraId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("ArtistaId", "DisqueraId");

                    b.HasIndex("DisqueraId");

                    b.ToTable("ArtistaDisquera");
                });

            modelBuilder.Entity("WebApiMusic.Entidades.Disquera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("disquera");
                });

            modelBuilder.Entity("WebApiMusic.Entidades.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Album")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisqueraId")
                        .HasColumnType("int");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("DisqueraId");

                    b.ToTable("musica");
                });

            modelBuilder.Entity("WebApiMusic.Entidades.ArtistaDisquera", b =>
                {
                    b.HasOne("WebApiMusic.Entidades.Artista", "Artista")
                        .WithMany("ArtistaDisquera")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiMusic.Entidades.Disquera", "Disquera")
                        .WithMany("ArtistaDisquera")
                        .HasForeignKey("DisqueraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("Disquera");
                });

            modelBuilder.Entity("WebApiMusic.Entidades.Music", b =>
                {
                    b.HasOne("WebApiMusic.Entidades.Disquera", "Disquera")
                        .WithMany("Music")
                        .HasForeignKey("DisqueraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disquera");
                });

            modelBuilder.Entity("WebApiMusic.Entidades.Artista", b =>
                {
                    b.Navigation("ArtistaDisquera");
                });

            modelBuilder.Entity("WebApiMusic.Entidades.Disquera", b =>
                {
                    b.Navigation("ArtistaDisquera");

                    b.Navigation("Music");
                });
#pragma warning restore 612, 618
        }
    }
}
